services:
  kyber-core:
    image: ghcr.io/smurfy7625-commits/kybercore:latest
    container_name: kyber-core
    restart: unless-stopped

    ports:
      - "8088:8088"

    environment:
      TZ: UTC

      PUID: 1000
      PGID: 100

      COMPOSE_ROOT: /host/Compose
      STORAGE_ROOT: /host/srv
      BACKUP_ROOT: /app/config/backups

      OMV_BRIDGE_SOCKET: /run/kyber-omv/bridge.sock

      OLLAMA_URL: ""
      OLLAMA_MODEL: qwen3:4b

      AUTH_SESSION_SECONDS: 43200
      AUTH_COOKIE_SECURE: "false"

      HOST_COMPOSE_ROOT: /opt/compose
      HOST_STORAGE_ROOT: /srv

    volumes:
      - ./config:/app/config
      - /opt/compose:/host/Compose
      - /srv:/host/srv
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/kyber-omv:/run/kyber-omv

    dns:
      - 1.1.1.1
      - 8.8.8.8

    pull_policy: always
